language: python
python: 3.6

script:
- pip install hoedown pyrss2gen flask gitpython
- cp -r ./document ./silverblog/document
- cp -r ./config ./silverblog/config
- cp -r templates ./silverblog/templates
- cd silverblog
- git clone https://${github_key}@github.com/${github_repo} static_page
- python manage.py build-page