version: '3'
services:
  silverblog:
    image: "silverblog/silverblog"
    tty: true
    container_name: "silverblog"
    restart: on-failure:10
    command: python3 watch.py
    volumes:
     - ./:/home/silverblog/
    ports:
     - "127.0.0.1:5000:5000"
  silverblog_control:
    image: "silverblog/silverblog"
    tty: true
    container_name: "silverblog_control"
    restart: on-failure:10
    command: python3 watch.py --control
    volumes:
     - ./:/home/silverblog/
    ports:
     - "127.0.0.1:5001:5001"

