FROM silverblog/silverblog
WORKDIR /home/silverblog/
COPY ./ ./
RUN apk add --no-cache nginx \
&& pip3 install supervisor
&& rm /etc/nginx/conf.d/default.conf \
&& echo "{\"install\":\"docker-buildin\"}" > install/install.lock
RUN bash ./install/initialization.sh \
&& cp example/supervisor-buildin.conf supervisor.conf
CMD [ "/usr/bin/supervisord","-c","/home/silverblog/supervisor.conf" ]