version: '2'
services:
  silverblog:
    image: "silverblog/silverblog"
    restart: always
    command: python3 watch.py --docker
    volumes:
     - ./:/home/silverblog/
    ports:
     - "127.0.0.1:5000:5000"
  silverblog_control:
    image: "silverblog/silverblog"
    restart: always
    command: uwsgi --json uwsgi.json:control
    volumes:
     - ./:/home/silverblog/
    ports:
     - "127.0.0.1:5001:5001"

