# These are supported funding model platforms

patreon: qwe7002
custom: ["https://get-telegram-sms.reall.uk/donate/paypal","https://get-telegram-sms.reall.uk/donate/unionpay","https://get-telegram-sms.reall.uk/donate/alipay"]
