image: docker.reallserver.cn/public/docker-git
stages:
  - build_docker_demo
  - docker_push
release_github: 
  only:
  - master
  script:
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:master

build_docker_demo:
  stage: build_docker_demo
  tags:
  - docker-build
  script:
  - docker build -t docker.reallserver.cn/silverblog/silverblog-demo -f ./example/demo/dockerfile .

docker_push:
  stage: docker_push
  tags:
  - docker-build
  script:
  - docker login -u qwe7002 -p ${docker_passwd} docker.reallserver.cn
  - docker push docker.reallserver.cn/silverblog/silverblog-demo
