
stages:
  - build
  - push
  - deploy

build_docker_demo:
  stage: build
  tags:
  - docker-build
  script:
  - docker build -t docker.reallserver.cn/silverblog/silverblog-demo -f ./example/demo/dockerfile .

release_github:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - master
  script:
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:master

docker_push:
  stage: push
  tags:
  - docker-build
  script:
  - docker login -u qwe7002 -p ${docker_passwd} docker.reallserver.cn
  - docker push docker.reallserver.cn/silverblog/silverblog-demo

demo_update:
  stage: deploy
  image: docker.reallserver.cn/public/docker-git
  script:
  - echo "$SSH_PRIVATE_KEY" > deploy.key
  - chmod 0600 deploy.key
  - ssh-add deploy.key
  - ssh qwe7002@demo.silverblog.org "bash start.sh"

