image: docker.reallserver.cn/public/docker-git

before_script:
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
release_github: 
  only:
  - master
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:master
  - git clone https://git.reallserver.cn:SilverBlog/SilverBlog.wiki.git wiki
  - cd wiki && git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.wiki.git HEAD:master