stages:
  - build
  - push
  - test
  - deploy

variables:
  docker_tag_name: "docker.reallserver.cn/silverblog/silverblog"

build_docker_demo:
  stage: build
  only:
  - develop
  tags:
  - docker-build
  script:
  - docker build -t ${docker_tag_name}-demo -f ./develop/demo/dockerfile .

release_github_nightly:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - nightly
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:nightly

release_github_master:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - master
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:master
  - git clone https://git.reallserver.cn/SilverBlog/SilverBlog.wiki.git wiki
  - cd wiki && git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.wiki.git HEAD:master

docker_push:
  stage: push
  only:
  - develop
  tags:
  - docker-build
  script:
  - docker login -u gitlab -p ${docker_passwd} docker.reallserver.cn
  - docker push ${docker_tag_name}-demo

unit_test:
  image: docker.reallserver.cn/silverblog/silverblog-demo
  stage: test
  script:
  - apk add --no-cache nginx
  - rm /etc/nginx/conf.d/default.conf && cp nginx_config /etc/nginx/conf.d/default.conf && mkdir /run/nginx
  - nginx && nohup python3 watch.py --control
  - python3 develop/unit_test/test.py

demo_update:
  stage: deploy
  only:
  - develop
  image: docker.reallserver.cn/public/docker-git
  script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > deploy.key
  - chmod 0600 deploy.key
  - ssh-add deploy.key
  - ssh qwe7002@demo.silverblog.org "docker-compose down && docker pull docker.reallserver.cn/silverblog/silverblog-demo && docker-compose up -d"

