stages:
  - build
  - push
  - test
  - deploy

variables:
  docker_tag_name: "docker.reallserver.cn/silverblog/silverblog"

build_docker_demo:
  stage: build
  only:
  - nightly
  tags:
  - docker-build
  script:
  - docker build -t ${docker_tag_name}-demo -f ./develop/demo/dockerfile .

release_github_nightly:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - nightly
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:nightly
  - git push --set-upstream https://${oschina_key}@gitee.com/qwe7002/silverblog.git HEAD:nightly

release_github_master:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - master
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:master
  - git push --set-upstream https://${oschina_key}@gitee.com/qwe7002/silverblog.git HEAD:master
  - git clone https://git.reallserver.cn/SilverBlog/SilverBlog.wiki.git wiki
  - cd wiki
  - git push -f --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.wiki.git HEAD:master
  - git push -f --set-upstream https://${oschina_key}@gitee.com/qwe7002/silverblog.wiki.git HEAD:master


docker_push:
  stage: push
  only:
  - nightly
  tags:
  - docker-build
  script:
  - docker login -u gitlab -p ${docker_passwd} docker.reallserver.cn
  - docker push ${docker_tag_name}-demo

unit_test:
  image: ubuntu:bionic
  stage: test
  only:
  - develop
  script:
  - apt-get update
  - apt-get install -y nginx uwsgi uwsgi-plugin-python3 python3-pip python3-wheel locales curl git
  - export LC_ALL="en_US.UTF-8" && export LC_CTYPE="en_US.UTF-8"
  - locale-gen en_US.UTF-8
  - cd install
  - bash install_python_dependency.sh
  - cd ..
  - bash ./install/initialization.sh
  - cp -f ./develop/demo/page.json ./config/page.json
  - cp -f ./develop/demo/system.json ./config/system.json
  - cp ./develop/demo/demo-article.md ./document/demo-article.md
  - python3 manage.py update
  - cd ./templates
  - curl https://raw.githubusercontent.com/SilverBlogTheme/clearision/master/install.sh | bash
  - cd ..
  - rm /etc/nginx/sites-enabled/default
  - cp ./nginx_config /etc/nginx/sites-enabled/silverblog
  - python3 watch.py &
  - python3 watch.py --control &
  - nginx
  - python3 develop/unit_test/test.py

demo_update:
  stage: deploy
  only:
  - nightly
  image: docker.reallserver.cn/public/docker-git
  script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > deploy.key
  - chmod 0600 deploy.key
  - ssh-add deploy.key
  - ssh qwe7002@demo.silverblog.org "docker-compose down && docker pull docker.reallserver.cn/silverblog/silverblog-demo && docker-compose up -d"

