image: docker.reallserver.cn/alpine-git

release_github: 
  only:
  - master
  script:
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git HEAD:master
develop_push_github: 
  only:
  - develop
  script:
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
  - git push --set-upstream https://${github_key}@github.com/qwe7002/SilverBlog.git HEAD:master