image: hedaqing/docker-alpine-git
push_to_github:
  only:
  - master
  script:
  - git checkout master --set-upstream http://git.reallserver.cn/SilverBlog/SilverBlog.git
  - git pull
  - git config --global http.proxy "http://192.168.3.1:1080"
  - git config --global https.proxy "http://192.168.3.1:1080"
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/SilverBlog.git
