FROM alpine:3.7

ENV LANG C.UTF-8

WORKDIR /home/silverblog/
COPY ./ /home/silverblog

RUN apk add --no-cache ca-certificates dumb-init bash git curl python3 uwsgi uwsgi-python3 \
&& apk add --no-cache --virtual .build-deps musl-dev gcc python3-dev \
&& cd /home/silverblog/install && bash container_install.sh\
&& apk del --purge .build-deps


RUN cp -f /home/silverblog/example/demo/page.json /home/silverblog/config/page.json \
&& cp -f /home/silverblog/example/demo/system.json /home/silverblog/config/system.json \
&& cp /home/silverblog/example/demo/demo-article.md /home/silverblog/document/demo-article.md \
&& python3 manage.py update
RUN cd /home/silverblog/templates \
&& curl https://raw.githubusercontent.com/SilverBlogTheme/clearision/master/install.sh | bash

CMD ["python3","watch.py","--docker","--control"]