FROM alpine:3.7

ENV LANG C.UTF-8

WORKDIR /home/silverblog/

RUN apk add --no-cache ca-certificates dumb-init bash git newt curl python3 uwsgi uwsgi-python3 \
&& apk add --no-cache --virtual .build-deps musl-dev gcc python3-dev \
&& pip3 install flask hoedown pypinyin pyrss2gen watchdog \
&& apk del --purge .build-deps

COPY ./ /home/silverblog
RUN bash /home/silverblog/install/install.sh \
&& cp -f /home/silverblog/example/demo/page.json /home/silverblog/config/page.json \
&& cp -f /home/silverblog/example/demo/system.json /home/silverblog/config/system.json \
&& cp /home/silverblog/example/demo/demo-article.md /home/silverblog/document/demo-article.md \
&& python3 manage.py update
RUN cd /home/silverblog/templates \
&& curl https://raw.githubusercontent.com/SilverBlogTheme/clearision/master/install.sh | bash

CMD ["python3","watch.py","--docker","--control"]